paths:
  /login:
    post:
      operationId: login
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      - name: password
        in: path
        required: true
        schema:
          type: string
