paths:
  /login:
    post:
      operationId: login
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: password
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful login to the system
        default:
          description: login user to the system
