---
micronaut:
  application:
    name: contacts-keeper
  server:
    context-path: /
    cors:
      enabled: true
---
datasources.default: {}
---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/contactskeeper
    driverClassName: com.mysql.cj.jdbc.Driver
    username: zoran
    password: MySQLzoranvasilic3!
    schema-generate: CREATE
    dialect: MYSQL


---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    intercept-url-map:
      -
        pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        access:
          - isAnonymous()
      - pattern: /redoc/**
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:password90characterslongshouldbe}"
              #base64: true
              #jws-algorithm: HS256
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
